services:
  db-fdw:
    build:
      dockerfile: db.Dockerfile
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - db_fdw_data:/home/postgres/pgdata/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-keesense}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-keesense}
      POSTGRES_DB: ${POSTGRES_DB:-keesense}

volumes:
  db_fdw_data:
